name: Check and validate Terraform live modules

'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Check and validate Terraform live modules
    runs-on: 'ubuntu-latest'

    services:
      moto:
        image: motoserver/moto:4.0.9
        ports:
          - 4566:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.x
      - name: Checking Terraform formatting style
        run: |
          make check-fmt
      - name: Initializing Terraform live modules
        run: |
          make init
      - name: Validating Terraform live modules
        run: |
          make validate
