name: Check and validate Terraform live modules

'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Check and validate Terraform live modules
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start moto container
        run: |
          docker run --detach --name moto --publish 4566:5000 --volume "${PWD}/config/amis.json:/amis.json" --env MOTO_AMIS_PATH=/amis.json --env MOTO_IAM_LOAD_MANAGED_POLICIES=true --rm motoserver/moto:5.0.20
      - name: Wait for moto container to be ready
        timeout-minutes: 1
        run: |
          while ! curl --fail --silent http://localhost:4566/moto-api/ > /dev/null ; do
            echo "Waiting for moto container to be ready..."
            sleep 2
          done
      - name: Setup Terraform
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.x
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4
      - name: Checking Terraform formatting style
        run: |
          make check-fmt
      - name: Linting Terraform live modules
        run: |
          make tflint
      - name: Initializing Terraform live modules
        run: |
          make init
      - name: Validating Terraform live modules
        run: |
          make validate
      - name: Generating Terraform live modules plans
        run: |
          make plan
      - name: Applying and destroying Terraform live modules plans
        run: |
          make apply-and-destroy
      - name: Stop moto container
        if: always()
        run: |
          docker stop moto
